Resources:
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.resourceNamePrefix}-items
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: ItemId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: ItemId
          AttributeType: S
